# Generated by Django 4.1.4 on 2022-12-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('option', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=2)),
            ],
        ),
    ]
