# Generated by Django 4.1.4 on 2022-12-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='working',
        ),
    ]
